"""initial schema

Revision ID: 4747273eff12
Revises: 
Create Date: 2026-04-22 15:55:18.790571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4747273eff12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('external_crm_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_cache',
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_in', sa.Integer(), nullable=False),
    sa.Column('token_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('meeting_type', sa.Text(), nullable=True),
    sa.Column('recall_bot_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('requested','joining','in_call','processing','done','failed')", name='ck_meetings_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recall_bot_id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('due_hint', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('open','done','dropped')", name='ck_action_items_status'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_items_meeting', 'action_items', ['meeting_id'], unique=False)
    op.create_table('dead_letter_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_kind', sa.Text(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('open','resolved','wont_fix','circuit_open')", name='ck_dlq_status'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dlq_status', 'dead_letter_jobs', ['status'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type in ('objection','feature_request','competitor_mention','risk','commitment','customer_goal','urgency')", name='ck_insights_type'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insights_meeting', 'insights', ['meeting_id'], unique=False)
    op.create_table('meeting_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('persisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.CheckConstraint("source in ('recall','internal')", name='ck_meeting_events_source'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_meeting_events_dedupe_key')
    )
    op.create_index('ix_meeting_events_event_type', 'meeting_events', ['event_type'], unique=False)
    op.create_index('ix_meeting_events_meeting_id_event_timestamp', 'meeting_events', ['meeting_id', 'event_timestamp'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('summary_type', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(content_markdown, ''))", persisted=True), nullable=True),
    sa.CheckConstraint("summary_type in ('executive_summary','followup_email','crm_note')", name='ck_summaries_type'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summaries_content_tsv', 'summaries', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_summaries_meeting_type', 'summaries', ['meeting_id', 'summary_type'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('remote_addr', postgresql.INET(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_deliveries_meeting_id', 'webhook_deliveries', ['meeting_id'], unique=False)
    op.create_index('ix_webhook_deliveries_received_at', 'webhook_deliveries', ['received_at'], unique=False, postgresql_ops={'received_at': 'DESC'})
    op.create_table('transcript_utterances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.BigInteger(), nullable=True),
    sa.Column('speaker_label', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('text_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(text, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['meeting_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_utterances_meeting_start', 'transcript_utterances', ['meeting_id', 'start_ms'], unique=False)
    op.create_index('ix_utterances_text_tsv', 'transcript_utterances', ['text_tsv'], unique=False, postgresql_using='gin')
    op.create_table('insight_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('utterance_id', sa.UUID(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utterance_id'], ['transcript_utterances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_evidence_insight', 'insight_evidence', ['insight_id'], unique=False)
    op.create_table('utterance_spans',
    sa.Column('utterance_id', sa.UUID(), nullable=False),
    sa.Column('recall_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('persisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utterance_id'], ['transcript_utterances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utterance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utterance_spans')
    op.drop_index('ix_insight_evidence_insight', table_name='insight_evidence')
    op.drop_table('insight_evidence')
    op.drop_index('ix_utterances_text_tsv', table_name='transcript_utterances', postgresql_using='gin')
    op.drop_index('ix_utterances_meeting_start', table_name='transcript_utterances')
    op.drop_table('transcript_utterances')
    op.drop_index('ix_webhook_deliveries_received_at', table_name='webhook_deliveries', postgresql_ops={'received_at': 'DESC'})
    op.drop_index('ix_webhook_deliveries_meeting_id', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_summaries_meeting_type', table_name='summaries')
    op.drop_index('ix_summaries_content_tsv', table_name='summaries', postgresql_using='gin')
    op.drop_table('summaries')
    op.drop_index('ix_meeting_events_meeting_id_event_timestamp', table_name='meeting_events')
    op.drop_index('ix_meeting_events_event_type', table_name='meeting_events')
    op.drop_table('meeting_events')
    op.drop_index('ix_insights_meeting', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_dlq_status', table_name='dead_letter_jobs')
    op.drop_table('dead_letter_jobs')
    op.drop_index('ix_action_items_meeting', table_name='action_items')
    op.drop_table('action_items')
    op.drop_table('meetings')
    op.drop_table('llm_cache')
    op.drop_table('accounts')
    # ### end Alembic commands ###
